version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    container_name: braintumorai_backend
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models  # Map model folder to allow updating model without rebuild
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: app/frontend/Dockerfile
    container_name: braintumorai_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/predict
